title: Entity Summarization
google_analytics: UA-47223641-5
description: Entity summarization is the problem of identifying a limited number of ordered RDF triples that summarize an entity in the best way—the result is typically presented in knowledge panels.
